# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20170806_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
