# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_id',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
