# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170815_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.WalletProfile'),
        ),
    ]
