# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '__first__'),
        ('accounts', '0008_remove_userprofile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallets.WalletProfile'),
        ),
    ]
