# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_num', models.CharField(blank=True, max_length=40, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.UserProfile')),
            ],
        ),
    ]
