# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_walletprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='userprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.UserProfile'),
        ),
    ]
