# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170816_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.UserProfile'),
        ),
    ]
