# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20170816_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletprofile',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
