# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170816_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
