# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170816_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='wallet_num',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
