# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170816_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
