# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170816_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletprofile',
            name='wallet_num',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='num',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
